### ISSUE TITLE
`/spigot/get_and_build_spigot.sh` fails

### ISSUE THREAD

**Issue by benjajaja** [ProgrammerDan/civcraft-vm#2]
got a new one :P

```
==> default: Error: /spigot/get_and_build_spigot.sh returned 148 instead of one of [0]
==> default: Error: /Stage[main]/Civcraft/Exec[civcraft.spigotcreate]/returns: change from notrun to 0 failed: /spigot/get_and_build_spigot.sh returned 148 instead of one of [0]
==> default: Debug: Executing '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python-software-properties'
==> default: Notice: /Stage[main]/Tools/Package[python-software-properties]/ensure: ensure changed 'purged' to 'latest'
==> default: Debug: /Package[python-software-properties]: The container Class[Tools] will propagate my refresh event
==> default: Debug: Executing '/usr/bin/dpkg-query -W --showformat '${Status} ${Package} ${Version}\n' software-properties-common'
==> default: Debug: Executing '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install software-properties-common'
==> default: Notice: /Stage[main]/Tools/Package[software-properties-common]/ensure: ensure changed 'purged' to 'latest'
==> default: Debug: /Package[software-properties-common]: The container Class[Tools] will propagate my refresh event
==> default: Debug: Exec[tmux.apt-add-repository](provider=posix): Executing '/usr/bin/sudo /usr/bin/apt-add-repository -y ppa:pi-rho/dev'
==> default: Debug: Executing '/usr/bin/sudo /usr/bin/apt-add-repository -y ppa:pi-rho/dev'
==> default: Notice: /Stage[main]/Tools/Exec[tmux.apt-add-repository]/returns: executed successfully
==> default: 
==> default: Debug: /Stage[main]/Tools/Exec[tmux.apt-add-repository]: The container Class[Tools] will propagate my refresh event
==> default: Debug: Exec[tmux.apt-update](provider=posix): Executing '/usr/bin/sudo /usr/bin/apt-get update'
==> default: Debug: Executing '/usr/bin/sudo /usr/bin/apt-get update'
==> default: Notice: /Stage[main]/Tools/Exec[tmux.apt-update]/returns: executed successfully
==> default: Debug: /Stage[main]/Tools/Exec[tmux.apt-update]: The container Class[Tools] will propagate my refresh event
==> default: Debug: Exec[tmux.install](provider=posix): Executing '/usr/bin/sudo /usr/bin/apt-get -y install tmux=1.9a-1~ppa1~p'
==> default: Debug: Executing '/usr/bin/sudo /usr/bin/apt-get -y install tmux=1.9a-1~ppa1~p'
==> default: Notice: /Stage[main]/Tools/Exec[tmux.install]/returns: executed successfully
==> default: Debug: /Stage[main]/Tools/Exec[tmux.install]: The container Class[Tools] will propagate my refresh event
==> default: Debug: Class[Tools]: The container Stage[main] will propagate my refresh event
==> default: Notice: /Stage[main]/Civcraft/File[civcraft.spigotcontrol]: Dependency Exec[civcraft.spigotcreate] has failures: true
==> default: Warning: /Stage[main]/Civcraft/File[civcraft.spigotcontrol]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Civcraft/Exec[civcraft.spigotserver]: Dependency Exec[civcraft.spigotcreate] has failures: true
==> default: Warning: /Stage[main]/Civcraft/Exec[civcraft.spigotserver]: Skipping because of failed dependencies
==> default: Debug: Class[Civcraft]: The container Stage[main] will propagate my refresh event
==> default: Debug: Finishing transaction 69983527214400
==> default: Debug: Storing state
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Debug: Stored state in 0.01 seconds
==> default: Notice: Finished catalog run in 538.10 seconds
==> default: Debug: Using settings: adding file resource 'rrddir': 'File[/var/lib/puppet/rrd]{:backup=>false, :group=>"puppet", :loglevel=>:debug, :owner=>"puppet", :mode=>"750", :links=>:follow, :path=>"/var/lib/puppet/rrd", :ensure=>:directory}'
==> default: Debug: /File[/var/lib/puppet/rrd]/ensure: created
==> default: Debug: Finishing transaction 69983540723160
==> default: Debug: Received report to process from ubuntu-server-12042-x64-vbox4210
==> default: Debug: Processing report from ubuntu-server-12042-x64-vbox4210 with processor Puppet::Reports::Store
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by ProgrammerDan** [comment]
Please SSH into the vagrant box, and paste here or link to a pastebin the contents of the Spigot build command -- should be in /spigot-build/ as a log file of some sort, blanking on exact naming.

**Comment by benjajaja** [comment]
Just had a brainfart, `ssh` wants the port specified with `-p` not next to the hostname.  
anyway here's the tail of the log:

```
Downloaded: https://hub.spigotmc.org/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar (245 KB at 389.6 KB/sec)
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/signature/java16/1.1/java16-1.1.signature
Jun 8, 2015 6:08:29 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.maven.wagon.providers.http.httpclient.NoHttpResponseException) caught when processing request to {s}->https://repo.maven.apache.org:443: The target server failed to respond
Jun 8, 2015 6:08:29 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
Jun 8, 2015 6:08:29 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.maven.wagon.providers.http.httpclient.NoHttpResponseException) caught when processing request to {s}->https://repo.maven.apache.org:443: The target server failed to respond
Jun 8, 2015 6:08:29 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
Jun 8, 2015 6:08:29 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.maven.wagon.providers.http.httpclient.NoHttpResponseException) caught when processing request to {s}->https://repo.maven.apache.org:443: The target server failed to respond
Jun 8, 2015 6:08:29 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:19 min
[INFO] Finished at: 2015-06-08T18:08:29+00:00
[INFO] Final Memory: 16M/57M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check (default) on project bukkit: Failed to obtain signature: org.codehaus.mojo.signature:java16:1.1: Could not transfer artifact org.codehaus.mojo.signature:java16:signature:1.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org:443 failed to respond
[ERROR] org.codehaus.mojo.signature:java16:signature:1.1
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true),
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Exception in thread "main" java.lang.RuntimeException: Error running command, return status !=0: [sh, /spigot-build/apache-maven-3.2.5/bin/mvn, clean, install]
    at org.spigotmc.builder.Builder.runProcess(Builder.java:492)
    at org.spigotmc.builder.Builder.main(Builder.java:373)
```

**Comment by benjajaja** [comment]
I'm trying to run the spigot build script again from the vm now, will report back

**Comment by ProgrammerDan** [comment]
Ah yeah, the scripts currently aren't very forgiving for one-off failures like maven repos not responding and the like. Go ahead and leave this issue open, as a reminder to puppetize this more fully so I can gain (1) idempotent actions and (2) retries on obvious failures like this

**Comment by ProgrammerDan** [comment]
@gipsy-king by-the-by any luck on round 2?

**Comment by benjajaja** [comment]
Had to leave, script standed at executing minecraft_something.sh, will report back later

**Comment by benjajaja** [comment]
It hanged there, did a `vagran provision` and `vagrant reload`, it did it.

Can we install civcraft's plugins latest version or something like that? Sorry if I'm naive, I have no idea how vagrant works.

**Comment by ProgrammerDan** [comment]
So, I haven't scripted the bits that will build and install Civcraft's plugins -- for now, that's an exercise for the user. What the script currently does do is well described in the readme, so I won't repeat it here; suffice it to say, it gets you a spigot server running the same version as Civcraft. So, you've got the locally compiled jar files to work with; the readme includes instructions on how to use them for development (as in, installing them into your local maven repository). 

I do need to update those instructions, as some experimentation last night working on the break-fix for civcraft revealed some inaccuracies in those instructions. That said, they'll get you pretty close.
